spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tasktrek_todo
    username: root
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org.hibernate.SQL: false #debug
    org.hibernate.orm.jdbc.bind: trace

