spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org.hibernate.SQL: false #debug
    org.hibernate.orm.jdbc.bind: trace

